// Auto-generated by deploy-ecosystem.js
// Last updated: 2026-06-19T08:56:34.636Z

export const VIBE_ECOSYSTEM_ADDRESSES: Record<number, {
  VibePoints: string;
  VibeIdentity: string;
  VibeSocial: string;
  DappCardRegistry: string;
}> = {
  [31337]: {
    VibePoints: '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512',
    VibeIdentity: '0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0',
    VibeSocial: '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9',
    DappCardRegistry: '0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9',
  },
};

// 积分配置
export const POINTS_REWARDS = {
  CREATE_PROFILE: '50',
  DAILY_SIGNIN: '5',
  INTERACTION: '10',
  ACTIVITY_HOST: '30',
  ACTIVITY_JOIN: '15',
  ACTIVITY_REWARD: '20',
  UGC_CARD: '20',
  CARD_USED: '1',
  INVITE: '100',
  FOLLOW: '2',
};

export const POINTS_COSTS = {
  PREMIUM_TEMPLATE: '100',
  PIN_ACTIVITY: '50',
  RARE_CARD_PACK: '30',
  PRIVATE_ACTIVITY: '20',
};
